### ISSUE TITLE
Add issue and pull request template

### ISSUE THREAD

**Issue by meanmachin3** [CircleCI-Public/swift-orb#13]
We could add this to have consistency across all other orbs project.  I would like to pick this up. Please consider adding the orbtoberfest label on the issue

**Comment by Shaedil** [comment]
Hey, I'd like to work on this issue. Would you mind assigning me this one and adding the orbtoberfest label?

**Comment by meanmachin3** [comment]
@Shaedil I'm waiting for it to be assigned to me so that I could start working on it 😅
